name: Upload Image

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'URL of the image to upload'
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download image
        run: curl -o image.png ${{ github.event.inputs.image_url }}

      - name: Commit image
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add image.png
          git commit -m "Add image"
          git push

      - name: Generate link
        id: generate-link
        run: |
          echo "::set-output name=image_url::https://github.com/${{ github.repository }}/raw/main/image.png"
